// Generated by https://quicktype.io

export class ResponseDto {
    code:     string;
    message:  string;
    state:    number;
    response: any;

    constructor () {
        this.code = '',
        this.message = '',
        this.state = 0
    }
}

